### PR TITLE
Issue #25

### PR DESCRIPTION
**Pull request by zanardigit**
See https://github.com/servergrove/ansible-symfony2/issues/25

Please review! And I'm a beginner, so you're allowed, nay, encouraged to insult me if I did something really wrong or just plain awful :-)

### CODE REVIEW

**Comment by zanardigit** [comment]
Ok so currently I have no clue about how to fix this. "defaults/main.yml" only accepts a flat dictionary of variable. The variable definition is not processed, so this will not work:

    ---
    # defaults file for symfony2
    ...
    symfony2_project_composer_opts: "{% if symfony2_project_env == 'prod' %} '--no-dev --optimize-autoloader --no-interaction' {% else %} '' {% endif %}"
    ...

Because that line will be taken as a string. If anyone with better knowledge than me would like to suggest a way to fix this PR, I'd be extremely grateful. If this is simply not possible with Ansible, that's ok too.

**Comment by maschmann** [comment]
@zanardigit sorry to respond that late: I'm in the middle of a large project (and a server migration of my private server) which leaves me with too little spare-time to react quickly in github.
I'll have a look into the PR as soon as I'm able :-(

**Comment by zanardigit** [comment]
@maschmann no problem at all, take your time. Thank you!

**Comment by maschmann** [comment]
@zanardigit if you need to change those vars, just use separate e.g. group_vars for different environments.
This makes it easier to manage than logic within configuration.

**Pull request closed without merging**
